name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload policy-service JAR
        uses: actions/upload-artifact@v3
        with:
          name: policy-artifact
          path: policy-service/target/policy-service-0.0.1-SNAPSHOT.jar

      - name: Upload claim-service JAR
        uses: actions/upload-artifact@v3
        with:
          name: claim-artifact
          path: claim-service/target/claim-service-1.0-SNAPSHOT.jar

      - name: Upload user-service JAR
        uses: actions/upload-artifact@v3
        with:
          name: user-artifact
          path: user-service/target/user-service-1.0-SNAPSHOT.jar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download policy-service JAR
        uses: actions/download-artifact@v3
        with:
          name: policy-artifact
          path: ./deploy-artifacts

      - name: Download claim-service JAR
        uses: actions/download-artifact@v3
        with:
          name: claim-artifact
          path: ./deploy-artifacts

      - name: Download user-service JAR
        uses: actions/download-artifact@v3
        with:
          name: user-artifact
          path: ./deploy-artifacts

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy policy service
        uses: azure/webapps-deploy@v2
        with:
          app-name: cloud-policy-service-543643725
          package: ./deploy-artifacts/policy-service-0.0.1-SNAPSHOT.jar

      - name: Deploy claim service
        uses: azure/webapps-deploy@v2
        with:
          app-name: cloud-claim-service-543643725
          package: ./deploy-artifacts/claim-service-1.0-SNAPSHOT.jar

      - name: Deploy user service
        uses: azure/webapps-deploy@v2
        with:
          app-name: cloud-user-service-543643725
          package: ./deploy-artifacts/user-service-1.0-SNAPSHOT.jar
